// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screenshots/AppStoreSlide1.tsx": () => import("../components/mockups/screenshots/AppStoreSlide1.tsx"),
  "./components/mockups/screenshots/AppStoreSlide2.tsx": () => import("../components/mockups/screenshots/AppStoreSlide2.tsx"),
  "./components/mockups/screenshots/AppStoreSlide3.tsx": () => import("../components/mockups/screenshots/AppStoreSlide3.tsx"),
  "./components/mockups/screenshots/AppStoreSlide4.tsx": () => import("../components/mockups/screenshots/AppStoreSlide4.tsx"),
  "./components/mockups/screenshots/AppStoreSlide5.tsx": () => import("../components/mockups/screenshots/AppStoreSlide5.tsx"),
  "./components/mockups/screenshots/AppStoreSlide6.tsx": () => import("../components/mockups/screenshots/AppStoreSlide6.tsx"),
  "./components/mockups/screenshots/AppStoreSlide7.tsx": () => import("../components/mockups/screenshots/AppStoreSlide7.tsx"),
  "./components/mockups/onboarding/GigGapScreen.tsx": () => import("../components/mockups/onboarding/GigGapScreen.tsx"),
  "./components/mockups/onboarding/GigGapScreenB.tsx": () => import("../components/mockups/onboarding/GigGapScreenB.tsx"),
  "./components/mockups/onboarding/GigGapScreenC.tsx": () => import("../components/mockups/onboarding/GigGapScreenC.tsx"),
  "./components/mockups/onboarding/GigGapScreenGlossy.tsx": () => import("../components/mockups/onboarding/GigGapScreenGlossy.tsx"),
  "./components/mockups/onboarding/GoalsScreen.tsx": () => import("../components/mockups/onboarding/GoalsScreen.tsx"),
  "./components/mockups/onboarding/PaywallScreen.tsx": () => import("../components/mockups/onboarding/PaywallScreen.tsx"),
  "./components/mockups/onboarding/RegistrationScreen.tsx": () => import("../components/mockups/onboarding/RegistrationScreen.tsx"),
  "./components/mockups/onboarding/WarmUpScreen.tsx": () => import("../components/mockups/onboarding/WarmUpScreen.tsx"),
  "./components/mockups/onboarding/WelcomeSequence.tsx": () => import("../components/mockups/onboarding/WelcomeSequence.tsx"),
  "./components/mockups/onboarding/WhatYouGetScreen.tsx": () => import("../components/mockups/onboarding/WhatYouGetScreen.tsx")
};
